name = "ratio-3-0"
main = "src/worker.ts"
compatibility_date = "2025-06-01"
account_id = "7f06c71e716a0e4a5d38073c16758c60"
workers_dev = true

# DATABASE_URL is a secret, set via `wrangler secret put DATABASE_URL` (done in CI).

[observability]
enabled = true
