// GENERATES packages/builder-core/src/theme/default-theme.generated.ts from the real, editable
// theme files under packages/builder-core/src/theme/default/. Run: npm run gen:default-theme.
// Commit the output so builder-core stays runtime-fs-free (the generated file is inline strings).
import fs from 'fs';
import path from 'path';
import prettier from 'prettier';

const srcDir = path.join(__dirname, '..', 'packages', 'builder-core', 'src', 'theme', 'default');
const dest = path.join(
  __dirname,
  '..',
  'packages',
  'builder-core',
  'src',
  'theme',
  'default-theme.generated.ts'
);

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

(async () => {
  const entries = walk(srcDir)
    .map(
      (full) =>
        [
          path.relative(srcDir, full).split(path.sep).join('/'),
          fs.readFileSync(full, 'utf8'),
        ] as const
    )
    .sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));

  const body = entries
    .map(([rel, content]) => `  ${JSON.stringify(rel)}: ${JSON.stringify(content)},`)
    .join('\n');

  const raw = `// GENERATED by scripts/gen-default-theme.ts from src/theme/default/. Do not edit by hand.
import type { ThemeFiles } from './bundle';

export const DEFAULT_THEME_FILES: ThemeFiles = {
${body}
};
`;

  const prettierConfig = await prettier.resolveConfig(dest);
  const out = await prettier.format(raw, { ...prettierConfig, parser: 'typescript' });

  fs.writeFileSync(dest, out);
  console.log('wrote', dest);
})().catch((e: unknown) => {
  console.error('gen-default-theme failed:', (e as Error).message);
  process.exit(1);
});
