// GENERATES the baked *-theme.generated.ts files from the real, editable theme directories under
// packages/builder-core/src/theme/library/<name>/. Run: npm run gen:themes. Commit the output so
// builder-core stays runtime-fs-free (the generated files are inline strings).
//
// `forma` is a FULL theme (the flagship / composition base). `nova`, `aura`, `atelier` hold only their
// DISTINCTIVE files — their *-theme.ts modules compose them over Forma, so shared chrome isn't
// duplicated. The generator doesn't care: it bakes whatever files a directory contains.
import fs from 'fs';
import path from 'path';
import prettier from 'prettier';

const themeRoot = path.join(__dirname, '..', 'packages', 'builder-core', 'src', 'theme', 'library');

const THEMES: { dir: string; out: string; exportName: string }[] = [
  { dir: 'forma', out: 'forma-theme.generated.ts', exportName: 'FORMA_THEME_FILES' },
  { dir: 'nova', out: 'nova-theme.generated.ts', exportName: 'NOVA_THEME_FILES' },
  { dir: 'aura', out: 'aura-theme.generated.ts', exportName: 'AURA_THEME_FILES' },
  { dir: 'atelier', out: 'atelier-theme.generated.ts', exportName: 'ATELIER_THEME_FILES' },
];

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

async function generate(theme: (typeof THEMES)[number]) {
  const srcDir = path.join(themeRoot, theme.dir);
  const dest = path.join(themeRoot, theme.out);
  const entries = walk(srcDir)
    .map(
      (full) =>
        [
          path.relative(srcDir, full).split(path.sep).join('/'),
          fs.readFileSync(full, 'utf8'),
        ] as const
    )
    .sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));

  const body = entries
    .map(([rel, content]) => `  ${JSON.stringify(rel)}: ${JSON.stringify(content)},`)
    .join('\n');

  const raw = `// GENERATED by scripts/gen-themes.ts from src/theme/library/${theme.dir}/. Do not edit by hand.
import type { ThemeFiles } from '../bundle';

export const ${theme.exportName}: ThemeFiles = {
${body}
};
`;

  const prettierConfig = await prettier.resolveConfig(dest);
  const out = await prettier.format(raw, { ...prettierConfig, parser: 'typescript' });
  fs.writeFileSync(dest, out);
  console.log('wrote', dest);
}

(async () => {
  for (const theme of THEMES) await generate(theme);
})().catch((e: unknown) => {
  console.error('gen-themes failed:', (e as Error).message);
  process.exit(1);
});
