// ADR-016 Phase 1 (OFCE-401): generate the control-plane SDK's types from the OpenAPI
// contract (the source of truth). Run: npm run gen:client. Commit the output so consumers
// don't need the generator. Keeps the SDK from drifting off the spec.
import openapiTS, { astToString } from 'openapi-typescript';
import fs from 'fs';
import path from 'path';
import { openApiDocument } from '../services/admin-api/openapi';

(async () => {
  const ast = await openapiTS(openApiDocument as unknown as Parameters<typeof openapiTS>[0]);
  const banner =
    '/* eslint-disable */\n// GENERATED by scripts/gen-client.ts from the OpenAPI spec. Do not edit by hand.\n';
  const dest = path.join(__dirname, '..', 'packages', 'control-plane-client', 'src', 'schema.ts');
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, banner + astToString(ast));
  console.log('wrote', dest);
})().catch((e: unknown) => {
  console.error('gen-client failed:', (e as Error).message);
  process.exit(1);
});
