// GENERATED by scripts/gen-client.ts from the OpenAPI spec. Do not edit by hand.
export interface paths {
  '/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The caller identity */
    get: operations['getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/stores': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Stores the caller may manage */
    get: operations['listStores'];
    put?: never;
    /** Onboard a store (caller becomes owner) */
    post: operations['createStore'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/stores/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tenant (store) id */
        id: string;
      };
      cookie?: never;
    };
    /** Read a store */
    get: operations['getStore'];
    put?: never;
    post?: never;
    /** Provable hard-delete */
    delete: operations['deleteStore'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/stores/{id}/page': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tenant (store) id */
        id: string;
      };
      cookie?: never;
    };
    /** Read one page by path */
    get: operations['getPage'];
    /** Create or replace a page (edits the live store) */
    put: operations['putPage'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/stores/{id}/domains': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tenant (store) id */
        id: string;
      };
      cookie?: never;
    };
    /** Domains mapped to the store + status */
    get: operations['listDomains'];
    put?: never;
    /** Connect a custom domain; returns DNS records to add */
    post: operations['connectDomain'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/stores/{id}/agent-tokens': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tenant (store) id */
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mint a short-lived agent token scoped to this store (ADR-007) */
    post: operations['mintAgentToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Identity: {
      userId: string;
      isPlatformAdmin: boolean;
    };
    StoreSummary: {
      id: string;
      name: string;
      role: string;
      host?: string | null;
      hosts: string[];
    };
    StoreCreate: {
      id: string;
      name: string;
      host: string;
      color?: string;
    };
    StoreCreated: {
      id: string;
      url: string;
    };
    Store: {
      id: string;
      name: string;
      theme?: {
        [key: string]: unknown;
      };
    };
    PageInput: {
      /** @description must start with / */
      path: string;
      pageType?: string;
      pageConfig: {
        [key: string]: unknown;
      };
    };
    Page: {
      path: string;
      pageType?: string;
      pageConfig: {
        [key: string]: unknown;
      };
    };
    DomainStatus: {
      host: string;
      kind: string;
      status: string;
      sslStatus?: string;
    };
    DomainConnection: {
      host: string;
      configured: boolean;
      status?: string;
      sslStatus?: string;
      apex?: boolean;
      cnameTarget?: string;
      records?: {
        type?: string;
        name?: string;
        host?: string;
        value?: string;
        ttl?: string;
        purpose?: string;
      }[];
    };
    AgentToken: {
      token: string;
      scope: string[];
      expiresIn: number;
    };
    DeleteProof: {
      residual: number;
      removed?: {
        [key: string]: unknown;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Identity'];
        };
      };
    };
  };
  listStores: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            stores: components['schemas']['StoreSummary'][];
          };
        };
      };
    };
  };
  createStore: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StoreCreate'];
      };
    };
    responses: {
      /** @description created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StoreCreated'];
        };
      };
    };
  };
  getStore: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tenant (store) id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Store'];
        };
      };
      /** @description forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteStore: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tenant (store) id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description delete proof */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeleteProof'];
        };
      };
    };
  };
  getPage: {
    parameters: {
      query: {
        path: string;
      };
      header?: never;
      path: {
        /** @description Tenant (store) id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page'];
        };
      };
      /** @description not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  putPage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tenant (store) id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PageInput'];
      };
    };
    responses: {
      /** @description ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page'];
        };
      };
      /** @description invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listDomains: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tenant (store) id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            domains: components['schemas']['DomainStatus'][];
          };
        };
      };
    };
  };
  connectDomain: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tenant (store) id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          host: string;
        };
      };
    };
    responses: {
      /** @description connected */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainConnection'];
        };
      };
      /** @description invalid host */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  mintAgentToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tenant (store) id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description minted */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AgentToken'];
        };
      };
    };
  };
}
